/*
 * Curriculum + IBJJF rules data for the BJJ Belt Progression app.
 *
 * Curriculum requirements are a sensible default syllabus — the IBJJF does not
 * mandate a technique curriculum, so academies should adapt these lists.
 * Rules summaries are based on the IBJJF rulebook; always confirm against the
 * current official rulebook at ibjjf.com before competing.
 */

const POINTS_TABLE = [
  { move: "Takedown", pts: 2 },
  { move: "Sweep", pts: 2 },
  { move: "Knee on belly", pts: 2 },
  { move: "Guard pass", pts: 3 },
  { move: "Mount", pts: 4 },
  { move: "Back mount", pts: 4 },
  { move: "Back control (hooks in)", pts: 4 },
];

const ILLEGAL_ALL = [
  "Heel hooks (gi — all belts; no-gi legal only at brown/black adult)",
  "Knee reaping (gi — all belts; no-gi legal only at brown/black adult)",
  "Slams (including slamming to escape submissions)",
  "Scissor takedown (kani basami)",
  "Neck cranks / cervical locks without a choke",
  "Spine locks without a choke",
  "Suplex takedowns landing opponent on head/neck",
  "Striking, biting, eye gouging, hair pulling, small-joint (finger) manipulation",
];

const TRACKS = {
  adult: {
    label: "Adult (16+)",
    belts: [
      {
        id: "white",
        name: "White Belt",
        color: "#f4f4f4",
        textColor: "#222",
        goal: "Survive, build a base, and learn the fundamental positions. Complete every requirement to unlock Blue Belt.",
        curriculum: {
          "Positions & Fundamentals": [
            "Breakfalls (back, side, forward roll)",
            "Shrimp (hip escape) and bridge movements",
            "Technical stand-up",
            "Hold and understand closed guard",
            "Hold and understand half guard",
            "Hold and understand side control",
            "Hold and understand mount",
            "Hold and understand back control (hooks/seatbelt)",
            "Hold and understand knee on belly",
            "Turtle position basics",
            "Standing posture, grips, and base",
          ],
          "Offense — Takedowns & Sweeps": [
            "Double leg takedown",
            "O-soto-gari (or another basic trip)",
            "Scissor sweep from closed guard",
            "Hip bump sweep from closed guard",
            "Flower (pendulum) sweep from closed guard",
          ],
          "Offense — Passing & Control": [
            "Knee cut (knee slice) pass",
            "Torreando (bullfighter) pass",
            "Maintain side control with crossface and underhook",
            "Transition side control → mount",
            "Take the back from turtle",
          ],
          "Offense — Submissions": [
            "Cross collar choke from closed guard",
            "Cross collar choke from mount",
            "Armbar from closed guard",
            "Armbar from mount",
            "Americana from side control or mount",
            "Kimura from closed guard",
            "Guillotine choke",
            "Rear naked choke",
          ],
          "Defense & Escapes": [
            "Bridge and roll (upa) mount escape",
            "Elbow–knee mount escape",
            "Side control escape to guard recovery",
            "Side control escape to knees",
            "Back control escape",
            "Standing headlock escape",
            "Posture and frames inside closed guard",
            "Guard retention basics (knees to chest, frames)",
            "Armbar defense (hidden arm, stacking)",
            "Choke defense (hand fighting, chin tuck)",
            "Knowing when to tap — training safety",
          ],
        },
        rules: {
          matchTime: "5 minutes (Adult). Masters divisions: 5–6 minutes.",
          promotion: "Minimum age 16 to hold an adult white belt (younger athletes use the kids belt system). No IBJJF minimum time at white belt; typical academy time is 1–2 years.",
          legal: [
            "All chokes with the gi or arms (no wind pipe pressure with fingers)",
            "Straight armlocks: armbar, americana, kimura",
            "Guillotine, rear naked choke, triangle, omoplata",
            "Straight ankle lock (foot lock)",
          ],
          newlyLegal: [],
          illegal: [
            "Wrist locks (legal from blue belt)",
            "Jumping to closed guard (forbidden for white belts)",
            "Kneebar, toe hold, calf slicer, bicep slicer (legal at brown/black)",
            ...ILLEGAL_ALL,
          ],
        },
      },
      {
        id: "blue",
        name: "Blue Belt",
        color: "#1e6bd6",
        textColor: "#fff",
        goal: "Build escapes into offense, develop open guards, and start chaining attacks. Complete every requirement to unlock Purple Belt.",
        curriculum: {
          "Positions & Guards": [
            "Butterfly guard (hooks, posture, grips)",
            "Spider guard fundamentals",
            "De La Riva guard fundamentals",
            "Deep half guard entries",
            "Half guard with underhook (knee shield)",
            "Open guard retention under pressure",
          ],
          "Offense — Takedowns & Sweeps": [
            "Single leg takedown",
            "Arm drag to back take or takedown",
            "Uchi mata or another hip throw",
            "Butterfly hook sweep",
            "De La Riva sweep (tripod or ball-and-chain)",
            "Lumberjack / tripod sweep vs standing opponent",
            "Half guard old-school sweep",
          ],
          "Offense — Passing": [
            "Over-under pass",
            "Double-under (stack) pass",
            "Leg drag pass",
            "Pressure passing vs half guard",
            "Passing spider/DLR grips safely",
          ],
          "Offense — Submissions": [
            "Triangle choke from guard",
            "Omoplata from guard",
            "Ezekiel choke",
            "Bow and arrow choke from back control",
            "Loop choke",
            "Wrist locks (now legal — from guard or top)",
            "Straight ankle lock with correct legal position",
            "Arm triangle (kata gatame) from mount/side",
            "Kimura from side control and north-south",
          ],
          "Defense & Escapes": [
            "Triangle choke escape (posture + stack)",
            "Omoplata escape (roll or posture out)",
            "Knee cut pass counter",
            "Leg lock defense fundamentals (boot, knee line)",
            "Deep half recovery from bad passes",
            "Escaping knee on belly",
            "Defending the back take (falling to the correct side)",
            "Guillotine defense (hand fight + sit-through)",
          ],
        },
        rules: {
          matchTime: "6 minutes (Adult).",
          promotion: "Minimum age 16. IBJJF minimum time at blue belt before purple: 2 years.",
          legal: [
            "Everything legal at white belt",
            "Straight ankle lock",
          ],
          newlyLegal: [
            "Wrist locks",
            "Jumping to closed guard (legal from blue belt up)",
          ],
          illegal: [
            "Kneebar, toe hold, calf slicer, bicep slicer (legal at brown/black)",
            ...ILLEGAL_ALL,
          ],
        },
      },
      {
        id: "purple",
        name: "Purple Belt",
        color: "#7c3aed",
        textColor: "#fff",
        goal: "Develop a personal game and connect techniques into systems. Complete every requirement to unlock Brown Belt.",
        curriculum: {
          "Positions & Guards": [
            "X guard entries and control",
            "Single leg X (ashi garami) — legal control without reaping",
            "Lasso guard",
            "Reverse De La Riva",
            "Crucifix position from turtle",
            "Body triangle back control",
          ],
          "Offense — Sweeps & Back Takes": [
            "X guard technical stand-up sweep",
            "Single leg X sweep",
            "Berimbolo or alternative DLR back take",
            "Arm drag from butterfly to back take",
            "Kimura trap to back take",
            "Half guard underhook back take",
          ],
          "Offense — Passing Systems": [
            "Body lock passing system",
            "Headquarters position — knee cut / long step / smash options",
            "Passing X guard and single leg X",
            "Float passing vs inverted guards",
          ],
          "Offense — Submissions": [
            "D'arce choke",
            "Anaconda choke",
            "North-south choke",
            "Baseball bat choke",
            "Crucifix attacks (chokes and armlocks)",
            "Triangle → armbar → omoplata chain",
            "Back attack system: choke / armbar off both sides",
            "Straight ankle lock finishing details",
          ],
          "Defense & Escapes": [
            "Escaping the body triangle",
            "D'arce and anaconda early defense",
            "Berimbolo counters",
            "Recomposing guard from leg drag",
            "Escaping the crucifix",
            "Late-stage submission escapes (safety and control)",
          ],
          "Knowledge": [
            "Assist teaching a fundamentals class",
            "Understand IBJJF scoring well enough to corner a teammate",
          ],
        },
        rules: {
          matchTime: "7 minutes (Adult).",
          promotion: "Minimum age 16. IBJJF minimum time at purple belt before brown: 18 months.",
          legal: [
            "Everything legal at blue belt (wrist locks, straight ankle lock, all chokes)",
          ],
          newlyLegal: [],
          illegal: [
            "Kneebar, toe hold, calf slicer, bicep slicer (legal at brown/black)",
            ...ILLEGAL_ALL,
          ],
        },
      },
      {
        id: "brown",
        name: "Brown Belt",
        color: "#6b4423",
        textColor: "#fff",
        goal: "Round out the complete game — the newly legal leg attacks, refined pressure, and coaching ability. Complete every requirement to unlock Black Belt.",
        curriculum: {
          "Newly Legal Weapons": [
            "Kneebar — entries from top and guard",
            "Toe hold — mechanics and legal application",
            "Calf slicer from the back / truck",
            "Bicep slicer awareness and application",
            "Leg entanglement system without reaping (gi-legal)",
            "Heel hook and reaping rules awareness for no-gi brown/black",
          ],
          "Offense — Refinement": [
            "A-game guard: 3-technique connected attack system",
            "A-game passing: 3-technique connected passing system",
            "Submission chains: 3+ attacks flowing from one control",
            "Takedown strategy for your build (wrestling or judo based)",
            "50/50 position offense and safety",
          ],
          "Defense & Escapes": [
            "Kneebar and toe hold defense",
            "Escaping 50/50 safely",
            "Defensive cycles: reguard from any pin",
            "Competition-pace submission defense",
          ],
          "Knowledge & Leadership": [
            "Teach a full class solo",
            "Referee or score a mock match correctly under IBJJF rules",
            "Corner a competitor through a full tournament match",
            "Design a 4-week training block for a lower belt",
          ],
        },
        rules: {
          matchTime: "8 minutes (Adult).",
          promotion: "Minimum age 18 for brown belt. IBJJF minimum time at brown belt before black: 1 year.",
          legal: [
            "Everything legal at purple belt",
          ],
          newlyLegal: [
            "Kneebar",
            "Toe hold",
            "Calf slicer",
            "Bicep slicer",
            "No-gi only: heel hooks and knee reaping (brown/black adult divisions)",
          ],
          illegal: [
            "Heel hooks and knee reaping in GI divisions (all belts)",
            ...ILLEGAL_ALL.slice(2),
          ],
        },
      },
      {
        id: "black",
        name: "Black Belt",
        color: "#111111",
        textColor: "#fff",
        goal: "Mastery is a practice, not a finish line. These are ongoing standards for a black belt.",
        curriculum: {
          "Ongoing Mastery": [
            "Maintain and evolve a complete gi and no-gi game",
            "Full command of IBJJF rules, scoring, and refereeing",
            "Mentor lower belts through their progression checklists",
            "Contribute to curriculum design at your academy",
            "Compete or coach at competition (optional but encouraged)",
            "First aid / injury awareness for running a mat",
          ],
        },
        rules: {
          matchTime: "10 minutes (Adult black belt).",
          promotion: "Minimum age 19. Degrees: 1st–3rd degree every 3 years, 4th–6th every 5 years; 7th (coral) after 7 years at 6th; 8th after 10 years at 7th; 9th (red belt) after 10 years at 8th.",
          legal: [
            "Everything legal at brown belt, including kneebar, toe hold, calf and bicep slicers",
            "No-gi only: heel hooks and knee reaping",
          ],
          newlyLegal: [],
          illegal: [
            "Heel hooks and knee reaping in GI divisions",
            ...ILLEGAL_ALL.slice(2),
          ],
        },
      },
    ],
  },

  kids: {
    label: "Kids (4–15)",
    belts: [
      {
        id: "kids-white",
        name: "White Belt",
        subtitle: "Ages 4+",
        color: "#f4f4f4",
        textColor: "#222",
        goal: "Learn to move safely, follow instructions, and enjoy the mat. Complete every requirement to unlock the Grey belts.",
        curriculum: {
          "Mat Skills & Safety": [
            "Breakfalls (back and side)",
            "Forward and backward rolls",
            "Shrimping down the mat",
            "Bridging (hips up!)",
            "Bear crawl / crab walk warm-ups",
            "Knowing how and when to tap",
            "Mat etiquette: bowing, listening, taking turns",
          ],
          "Positions": [
            "Closed guard (top and bottom)",
            "Mount (staying heavy with good posture)",
            "Side control (chest connection)",
            "Back control with seatbelt grip",
          ],
          "Offense": [
            "Scissor sweep",
            "Hip bump sweep",
            "Take the back from turtle",
            "Armbar from mount (slow and controlled)",
          ],
          "Defense": [
            "Bridge and roll (upa) mount escape",
            "Elbow–knee mount escape",
            "Side control escape to guard",
            "Standing up in base (technical stand-up)",
          ],
        },
        rules: {
          matchTime: "Mighty Mite (4–6): 2 min · Pee Wee (7–9): 3 min · Junior (10–12): 4 min · Teen (13–15): 4 min.",
          promotion: "Kids belt system covers ages 4–15. Grey belts available from age 4.",
          legal: [
            "Positional control and points (takedowns, sweeps, passes, mount, back)",
            "Straight armlocks (e.g. armbar) applied with control",
            "Basic gi chokes appropriate to age division (coach supervised)",
          ],
          newlyLegal: [],
          illegal: [
            "Guillotine, omoplata, triangle pulling the head, arm triangle, ezekiel (forbidden for ages 4–12)",
            "Wrist locks (forbidden for all kids divisions)",
            "All leg locks including straight ankle lock (forbidden for all kids divisions)",
            "Bicep slicers and calf slicers",
            ...ILLEGAL_ALL,
          ],
        },
      },
      {
        id: "kids-grey",
        name: "Grey Belt Family",
        subtitle: "Grey/White → Grey → Grey/Black · Ages 4+",
        color: "#9aa0a6",
        textColor: "#fff",
        goal: "Three steps: grey/white bar, solid grey, grey/black bar. Complete every requirement to unlock the Yellow belts.",
        curriculum: {
          "Movement & Positions": [
            "All white belt movements done smoothly",
            "Knee on belly with balance",
            "Turtle (safe posture, elbows in)",
            "Half guard (top and bottom)",
            "Grip fighting basics (gi grips)",
          ],
          "Offense": [
            "Double leg takedown with a safe landing",
            "O-soto-gari trip",
            "Flower (pendulum) sweep",
            "Guard pass: knee cut",
            "Guard pass: torreando",
            "Cross collar choke from mount (age-appropriate, supervised)",
            "Americana from side control (slow and controlled)",
            "Side control → mount transition",
          ],
          "Defense": [
            "Back escape",
            "Headlock escape",
            "Frames and posture inside someone's guard",
            "Guard retention: knees to chest",
          ],
          "Character": [
            "Helps younger/newer students",
            "Good attitude when losing a roll",
          ],
        },
        rules: {
          matchTime: "By age: Mighty Mite 2 min · Pee Wee 3 min · Junior 4 min · Teen 4 min.",
          promotion: "Grey/white, grey, and grey/black are earned in order. Minimum age 4.",
          legal: [
            "Everything from kids white belt",
          ],
          newlyLegal: [],
          illegal: [
            "Same restrictions as kids white belt — no wrist locks, no leg locks, no guillotine/omoplata/triangle-pulling-head/arm-triangle/ezekiel for ages 4–12",
            ...ILLEGAL_ALL,
          ],
        },
      },
      {
        id: "kids-yellow",
        name: "Yellow Belt Family",
        subtitle: "Yellow/White → Yellow → Yellow/Black · Ages 7+",
        color: "#f2c531",
        textColor: "#222",
        goal: "Three steps: yellow/white bar, solid yellow, yellow/black bar. Complete every requirement to unlock the Orange belts.",
        curriculum: {
          "Positions & Guards": [
            "Butterfly guard hooks and posture",
            "Open guard retention (feet on hips, frames)",
            "Back control with hooks — maintaining through rolls",
            "De La Riva hook introduction",
          ],
          "Offense": [
            "Single leg takedown finishing safely",
            "Arm drag from seated guard",
            "Butterfly hook sweep",
            "Tripod sweep vs standing opponent",
            "Armbar from closed guard",
            "Kimura from closed guard",
            "Rear naked choke with control (age-appropriate, supervised)",
            "Bow and arrow choke introduction (supervised)",
          ],
          "Defense": [
            "Armbar defense (hidden arm)",
            "Choke defense (hand fighting, chin down)",
            "Escaping knee on belly",
            "Sprawl vs takedowns",
          ],
          "Competition Knowledge": [
            "Knows the points: takedown 2, sweep 2, pass 3, mount 4, back 4",
            "Can explain what is illegal for their age division",
          ],
        },
        rules: {
          matchTime: "Pee Wee (7–9): 3 min · Junior (10–12): 4 min · Teen (13–15): 4 min.",
          promotion: "Yellow belts available from age 7.",
          legal: [
            "Everything from the grey belts",
          ],
          newlyLegal: [],
          illegal: [
            "Ages 7–12: still no guillotine, omoplata, triangle pulling the head, arm triangle, or ezekiel",
            "No wrist locks or leg locks in any kids division",
            ...ILLEGAL_ALL,
          ],
        },
      },
      {
        id: "kids-orange",
        name: "Orange Belt Family",
        subtitle: "Orange/White → Orange → Orange/Black · Ages 10+",
        color: "#e8842c",
        textColor: "#fff",
        goal: "Three steps: orange/white bar, solid orange, orange/black bar. Complete every requirement to unlock the Green belts.",
        curriculum: {
          "Positions & Guards": [
            "Spider guard grips and retention",
            "Half guard with knee shield",
            "Deep half guard introduction",
            "Body positioning for passing pressure",
          ],
          "Offense": [
            "Uchi mata or hip throw",
            "De La Riva sweep",
            "Old-school sweep from half guard",
            "Over-under pass",
            "Leg drag pass",
            "Triangle choke mechanics (drilled; legal in competition at 13+)",
            "Omoplata mechanics (drilled; legal in competition at 13+)",
            "Attack chains: collar choke → armbar from mount",
          ],
          "Defense": [
            "Triangle escape (posture and stack)",
            "Recovering guard from leg drag",
            "Defending the back take",
            "Guillotine defense (drilled)",
          ],
          "Competition Knowledge": [
            "Has competed or done in-house mock matches",
            "Understands advantages and penalties",
          ],
        },
        rules: {
          matchTime: "Junior (10–12): 4 min · Teen (13–15): 4 min.",
          promotion: "Orange belts available from age 10.",
          legal: [
            "Everything from the yellow belts",
            "At age 13+: guillotine, omoplata, triangle (pulling head), arm triangle, and ezekiel become legal in competition",
          ],
          newlyLegal: [],
          illegal: [
            "Ages 10–12: guillotine, omoplata, triangle pulling the head, arm triangle, ezekiel still forbidden",
            "No wrist locks or leg locks in any kids division",
            ...ILLEGAL_ALL,
          ],
        },
      },
      {
        id: "kids-green",
        name: "Green Belt Family",
        subtitle: "Green/White → Green → Green/Black · Ages 13+",
        color: "#2e8b57",
        textColor: "#fff",
        goal: "The last kids belts. Three steps: green/white bar, solid green, green/black bar. At 16, athletes transition to the adult system (typically blue belt at the professor's discretion).",
        curriculum: {
          "Now-Legal Techniques (13+)": [
            "Guillotine choke with control",
            "Triangle choke from guard",
            "Omoplata with safe finishing",
            "Arm triangle (kata gatame)",
            "Ezekiel choke",
          ],
          "Advanced Fundamentals": [
            "Connected guard attack system (2–3 techniques)",
            "Connected passing system (2–3 techniques)",
            "Pressure passing vs half guard",
            "Back attack system: choke and armbar off both sides",
            "Takedown chain: level change → double → single",
          ],
          "Defense": [
            "Late-stage escape safety (knowing when to tap early)",
            "Escaping body triangle",
            "D'arce/anaconda early defense (drilled)",
          ],
          "Leadership": [
            "Helps coach a kids fundamentals class",
            "Models good sportsmanship at competitions",
            "Understands the adult belt rules they'll transition into",
          ],
        },
        rules: {
          matchTime: "Teen (13–15): 4 minutes.",
          promotion: "Green belts available from age 13. At 16 the athlete moves to the adult system — a green belt typically transitions to blue belt (professor's discretion; IBJJF allows blue at 16).",
          legal: [
            "Everything from the orange belts",
            "Guillotine, omoplata, triangle (pulling head), arm triangle, ezekiel (ages 13–15)",
          ],
          newlyLegal: [
            "Guillotine choke",
            "Omoplata",
            "Triangle pulling the head",
            "Arm triangle",
            "Ezekiel choke",
          ],
          illegal: [
            "Wrist locks (legal only from adult blue belt)",
            "All leg locks including straight ankle lock (legal from adult white belt at 16+)",
            ...ILLEGAL_ALL,
          ],
        },
      },
    ],
  },
};
